[package]
name = "core"
version = "1.0.0"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "Main Package"
edition = "2021"

[dependencies]
utils = { path = "../utils" }


log = "0.4.20"
chrono = "0.4.31"
