name: Release

on:
  push:
    branches: [release]

jobs:
  release:
    name: giton-release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    continue-on-error: true
    outputs:
      upload_url: ${{ steps.automatic-release.outputs.upload_url }}
    steps:
      - id: automatic-release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          title: "giton-${{ github.ref_name }}"
          draft: true
          prerelease: false

  build-release:
    name: giton-cli
    needs: ["giton-release"]
    runs-on: ${{matrix.os}}
    env:
      CARGO: cargo
      TARGET_FLAGS: ""
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-18.04
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          targets: ${{ matrix.platform.target }}

      - name: install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt-get update

      - name: build
        run: cargo build --target ${{ matrix.target }} --release
